import type { Context } from "hono";
import { BRAND, CONTACT_EMAIL, PRIVACY_UPDATED } from "../constants.js";
import { PAGE } from "./shell.js";

const PRIVACY_BODY = `
<p>${BRAND} is operated by Lane Aasen (<a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>).</p>

<h2>Summary</h2>
<p>To get a forecast from ${BRAND}, users send a location, forecast options, and an anonymous
token generated by the app. There is no sign-up, name, email address, or password required.
${BRAND} uses no analytics, ads, or tracking.</p>

<h2>Account Token</h2>
<p>${BRAND} does not require an account. Instead, it uses an anonymous token that is created on
first launch. The token is a random value that is not tied to a name, phone number, email, or
device identifier. The account token is only used to count requests against usage limits.</p>

<h2>Data Retention</h2>
<p>The server stores one record per request including time of the request, location rounded to
1 km, forecast options, reply size, timing information, and account token. Phone numbers are not
stored. This data is stored for as long as the service runs. It is used for usage tracking and
may be used for training the encoder on real-world usage.</p>
<p>${BRAND} stores a token, previously decoded forecasts, settings, and downloaded offline maps
on your phone.</p>

<h2 id="deletion">Data Deletion</h2>
<p>Steps:</p>
<ol>
  <li>Open the ${BRAND} app.</li>
  <li>Tap the gear icon in the upper-right corner.</li>
  <li>Scroll down to "Delete account" and confirm.</li>
</ol>
<p>This immediately erases your token from the server and erases all data stored on your phone.
Request records are kept on the server with the token removed so that they can't be linked back
to you.</p>
<p>Data cannot be deleted outside the app, since the app's stored token is the only way a token
is linked to you. If you delete the app before deleting your account, the anonymous token will
remain on the server but there will be no way to link to you. Delete your account before deleting
the app if you want the token erased from the server.</p>

<h2>App Permissions</h2>
<p>${BRAND} asks for location permission when requesting a forecast. It never uses your location
in the background. Location permission is not required. If you don't want to grant location
permission, simply set the location option to "Custom" and pick a forecast location on the
map.</p>

<h2>Third Parties</h2>
<p>${BRAND} sells no data. Data is only shared with the following third parties for operation of
the service:</p>
<ul>
  <li>Open-Meteo: Forecast coordinates and options. No account token.</li>
  <li>Twilio: SMS requests and replies, including phone number. Twilio retains the phone number
  and message text for 30 days. Mobile information and SMS opt-in consent are never shared with
  third parties or affiliates for marketing or promotional purposes.</li>
  <li>Google Cloud: Server hosting and production database. Server logs are retained for 30
  days.</li>
  <li>Cloudflare: Serves maps.</li>
  <li>Expo: App update delivery.</li>
  <li>Carriers: Mobile carriers and satellite networks see your phone number and retain messages
  according to their own policies.</li>
  <li>Law enforcement: Only where required by law.</li>
</ul>

<h2>Text Messages</h2>
<p>${BRAND} only replies to forecast requests. It never sends marketing, recurring, or
unsolicited messages. ${BRAND} may send multiple messages in response to a forecast request if
"Multi-message forecast" is enabled in the app.</p>
<p>Message and data rates may apply. Reply STOP to opt out and HELP for help.</p>

<h2>Children</h2>
<p>${BRAND} is not directed to children under 13 and does not knowingly collect information from
them.</p>

<h2>Changes</h2>
<p>Changes to this policy are posted here and the date at the top is updated.</p>
`;

export function privacy(c: Context) {
  return c.html(PAGE("Privacy Policy", PRIVACY_BODY, { updated: PRIVACY_UPDATED }));
}
