// Shared layer stack for the previews: stack(prefix, {base, lc, hs}) is the full layer list
// for one archive set. Zoom/bounds gating lives on the sources. basemapStyle.ts is the app copy.
const LC = {
  forest: "#aac29e", grassland: "#d1d7b4", scrub: "#c4d0aa",
  farmland: "#ded9be", barren: "#d8d3c7", glacier: "#f2f8fc",
  urban_area: "#d5cfd3", wetland: "#c3d3c4",
};
// English where the source carries it (Protomaps places/earth/water), else the local name.
const nameEn = ["coalesce", ["get", "name:en"], ["get", "name"]];
const lcColor = ["match", ["get", "kind"], ...Object.entries(LC).flat(),
                 "#d8d3c7"];

// Full layer stack for one archive set. p = id prefix, src = {base, lc, hs}.
function stack(p, src) {
  const halo = { "text-halo-color": "#ffffff", "text-halo-width": 1.4 };
  return [
    { id: p + "earth", type: "fill", source: src.base, "source-layer": "earth",
      paint: { "fill-color": "#d8d3c7" } },
    { id: p + "landcover", type: "fill", source: src.lc,
      "source-layer": "landcover",
      paint: { "fill-color": lcColor, "fill-opacity": 1.0 } },
    { id: p + "glacier", type: "fill", source: src.base, "source-layer": "landuse",
      filter: ["==", ["get", "kind"], "glacier"],
      paint: { "fill-color": "#f2f8fc", "fill-opacity": 0.9 } },
    { id: p + "bare-rock", type: "fill", source: src.base,
      "source-layer": "landuse",
      filter: ["==", ["get", "kind"], "bare_rock"],
      paint: { "fill-color": "#cdc7bd", "fill-opacity": 0.7 } },
    { id: p + "hillshade", type: "raster", source: src.hs,
      paint: { "raster-opacity": 0.55, "raster-contrast": 0.25,
               "raster-resampling": "linear" } },
    { id: p + "water", type: "fill", source: src.base, "source-layer": "water",
      filter: ["==", ["geometry-type"], "Polygon"],
      paint: { "fill-color": "#a9c7dc" } },
    // Rivers: stock water lines from z9 (streams arrive at higher zooms than we carry).
    { id: p + "rivers", type: "line", source: src.base, "source-layer": "water",
      filter: ["==", ["geometry-type"], "LineString"],
      paint: { "line-color": "#a9c7dc",
               "line-width": ["interpolate", ["linear"], ["zoom"], 9, 0.8, 12, 2] } },
    { id: p + "boundaries-region", type: "line", source: src.base,
      "source-layer": "boundaries",
      filter: ["!=", ["get", "kind"], "country"],
      paint: { "line-color": "#9b909b", "line-width": 0.8,
               "line-dasharray": [3, 2] } },
    { id: p + "boundaries-country", type: "line", source: src.base,
      "source-layer": "boundaries",
      filter: ["==", ["get", "kind"], "country"],
      paint: { "line-color": "#8a7f8a", "line-width": 1.4 } },
    ...[[p + "water-labels", 0, 2], [p + "water-labels-mid", 9, 5],
        [p + "water-labels-all", 10, 99]].map(([id, minzoom, maxrank]) => ({
      id, type: "symbol", source: src.base, "source-layer": "water_labels",
      minzoom, ...(!id.endsWith("all") && { maxzoom: minzoom === 0 ? 9 : 10 }),
      filter: ["<=", ["coalesce", ["get", "rank"], 1], maxrank],
      layout: { "text-field": ["get", "name"],
                "text-font": ["Noto Sans Italic"], "text-size": 12,
                "text-padding": 8 },
      paint: { "text-color": "#4a7ba6", ...halo },
    })),
    { id: p + "glacier-labels", type: "symbol", source: src.base,
      "source-layer": "glacier_labels",
      layout: { "text-field": ["get", "name"],
                "text-font": ["Noto Sans Italic"], "text-size": 12 },
      paint: { "text-color": "#6a94b8", ...halo } },
    ...[[p + "peaks", 0, 2], [p + "peaks-mid", 9, 6],
        [p + "peaks-all", 10, 99]].map(([id, minzoom, maxrank]) => ({
      id, type: "symbol", source: src.base, "source-layer": "peaks",
      minzoom, ...(!id.endsWith("all") && { maxzoom: minzoom === 0 ? 9 : 10 }),
      filter: ["<=", ["coalesce", ["get", "rank"], 1], maxrank],
      layout: {
        "icon-image": "peak-triangle", "icon-size": 1, "text-optional": true,
        "text-field": ["case", ["has", "ele"],
          ["concat", ["get", "name"], "\n",
           ["number-format", ["round", ["*", ["get", "ele"], 3.28084]],
            { "max-fraction-digits": 0 }], " ft"],
          ["get", "name"]],
        "text-font": ["Noto Sans Medium"], "text-size": 12,
        "text-anchor": "top", "text-offset": [0, 0.6], "text-padding": 14,
        "symbol-sort-key": ["-", 9000, ["coalesce", ["get", "ele"], 0]],
      },
      paint: { "text-color": "#5a4636", ...halo },
    })),
    { id: p + "places-city", type: "symbol", source: src.base,
      "source-layer": "places",
      filter: ["==", ["get", "kind"], "locality"],
      layout: { "text-field": nameEn,
                "text-font": ["Noto Sans Regular"], "text-size": 12,
                "symbol-sort-key": ["coalesce", ["get", "min_zoom"], 10] },
      paint: { "text-color": "#3d3a38", ...halo } },
    { id: p + "places-region", type: "symbol", source: src.base,
      "source-layer": "places",
      filter: ["==", ["get", "kind"], "region"],
      layout: { "text-field": nameEn,
                "text-font": ["Noto Sans Regular"], "text-size": 12,
                "text-transform": "uppercase", "text-letter-spacing": 0.1 },
      paint: { "text-color": "#8a847e", ...halo } },
    { id: p + "places-country", type: "symbol", source: src.base,
      "source-layer": "places",
      filter: ["==", ["get", "kind"], "country"],
      layout: { "text-field": nameEn,
                "text-font": ["Noto Sans Medium"], "text-size": 14,
                "text-transform": "uppercase" },
      paint: { "text-color": "#54504e", ...halo } },
  ];
}

